### ISSUE TITLE
Go-Live checklist

### ISSUE THREAD

**Issue by andyundso** [flatfeestack/flatfeestack#237]
Platform:

- [ ] Point flatfeestack.io to DigitalOcean
- [ ] Test sign-up and sign-in
- [ ] Test starring a repository and check if analyzer result is sent back
- [ ] Update backend environment variables with Stripe secrets
- [ ] Test pay-in
- [ ] Check back next day if funds have been distributed

DAO:

- Decide if go-live happens with the DAO (upgradeable contract / DAO2). If yes (#147):
    - [ ] Configure named accounts
    - [ ] Configure network configuration for main net, including private keys for deployer
    - [ ] Do the deployment and check-in the resulting JSON files (prettify!)
    - [ ] Adapt payout configuration to point to contract addresses
    - [ ] Adapt forum configuration to point to DAO address
    - [ ] Once deployed, test if new voting slot can be created
    - [ ] Create a proposal for the new voting slot
    - [ ] Check if discussion has been created automatically created
- If no:
    - Discuss how the DAO should look like and if frontend should be adapted during this thesis
    - In any case, adapt frontend / payout to allow deactivating the DAO on production

Forum:

- [ ] Create a discussion
- [ ] Edit post
- [ ] Create a comment
- [ ] Edit comment
